#!/bin/sh
#    Copyright:  (C) 2011 Guo Wenxue<guowenxue@gmail.com>  
#                All rights reserved.
#
#  Description:  This shell script used to download the file by tftp(in busybox) 
#      Version:  1.0.0(12/16/2011~)
#                Author:  Guo Wenxue <guowenxue@gmail.com>

server=192.168.1.160

if [ $# -eq 1 ] ; then
   file=$1
elif [ $# -eq 2 ] ; then
   file=$1 
   server=$2 
else   
   echo "Usage: $0 FileName [ServerIP]"
   exit
fi
              
tftp -gr $file $server && chmod 777 $file
